### ISSUE TITLE
Publish on packagist

### ISSUE THREAD

**Issue by jankal** [deprecated-packages/ThemeIcanboogie#1]
@olvlvl It's yours. If you want to, you may publish it on packagist.

If you don't want to, should I?

**Comment by jankal** [comment]
@olvlvl I will commit required changes for publishing this on packagist.

**Comment by olvlvl** [comment]
Thanks @jankal!

**Comment by jankal** [comment]
@kukulich or @TomasVotruba I need "maintainership access" for the namespace `apigen` on packagist.org to publish this.

**Comment by kukulich** [comment]
I don't have the password for apigen on packagist :(

**Comment by jankal** [comment]
As I see, @TomasVotruba also has published the two themes there so he should have access.

@jadb seems to have main acoount.

**Comment by jankal** [comment]
@olvlvl After publish please remove https://packagist.org/packages/olvlvl/apipgen-theme-icanboogie from packagist.

**Comment by jankal** [comment]
Ping @TomasVotruba

**Comment by TomasVotruba** [comment]
This is not needed, as it will be part of ApiGen repo.
